apiVersion: v1
kind: Pod
metadata:
  name: order
spec:
  containers:
    - name: order
      image: fmo/order:1.0.0
      env:
        - name: APPLICATION_PORT
          value: "8080"
        - name: PAYMENT_SERVICE_URL
          value: "payment:8081"
